### ISSUE TITLE
Support for multi-get

### ISSUE THREAD

**Issue by davidbkemp** [gphat/wabisabi#16]
We would like to use multi-get, but Wabisabi does not seem to support it:
http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/docs-multi-get.html

**Comment by gphat** [comment]
Hey @davidbkemp!

@mmollaverdi was kind enough to contribute a patch to add multi-get and I've just released version 2.0.14 with his patch included. Yay!

**Comment by mmollaverdi** [comment]
David and I actually work together, I happened to be the one in immediate need of this feature, so I made a PR for it. Thanks for your really quick responses @gphat .

**Comment by gphat** [comment]
Ah, well it was still quite nice of you to put it together. Thanks @mmollaverdi and @davidbkemp!
