### ISSUE TITLE
how to close the client

### ISSUE THREAD

**Issue by 506764932** [gphat/wabisabi#22]
hi I'm using your client .
i created a index use the createIndex method. that is all in my simple program. but my program is still running. i think the reason is the thread of createIndex method created by client did not close. has any suggestion close the client?

**Comment by gphat** [comment]
Hey there! You can use `Client.shutdown()` to close all the HTTP-bits of wabisabi. I've documented this in the README to benefit future users!

**Comment by lisali008** [comment]
Client.shutdown() does not work. The program still running.

**Comment by lisali008** [comment]
have to call client.http.shutdown() to close properly.
