### ISSUE TITLE
How to retrieve hits with a scroll_id

### ISSUE THREAD

**Issue by developmentstudio** [gphat/wabisabi#30]
Hi Wabisabi maintainers,

At the moment I'm trying to get scan and scroll queries working via the Wabisabi elasticsearch client. So far, I be able to fire a scroll and scan query to Elasticsearch with the query below and obtain a _scroll_id. 

```
client.search("index", query, uriParameters = SearchUriParameters(searchType = Some(Scan), scroll = Some("10m")))
```

I can't figure out what the right way is to do the follow-up queries via the Wabisabi client to retrieve the actual documents from Elasticsearch. Can someone give me an example or pointers? @gphat, @mmollaverdi maybe?

**Comment by mmollaverdi** [comment]
Hi Kevin, there isn't support for making `scroll` requests through Wabisabi yet. I actually implemented this a few weeks ago but haven't pushed it yet, will make a PR tomorrow.

**Comment by developmentstudio** [comment]
Hi mmollaverdi, in that case I will wait till tomorrow, before hacking it together myself. :) Thanks!

**Comment by gphat** [comment]
Merged this will be releasing today as 2.1.3!

**Comment by developmentstudio** [comment]
Thanks! @mmollaverdi and @gphat

**Comment by wgodwin** [comment]
@developmentstudio can please you post the sample code on how to use scan and scroll with wabisabi?

**Comment by developmentstudio** [comment]
@wgodwin See the example below to get the idea how I implemented it. The example is not working code. Hope this will get you up and running.

```scala
// Your search query
val request = client.search(index, query, _type, SearchUriParameters(searchType = Some(Scan), scroll = Some("10m")))
request onComplete {
  case Success(r) =>
    // Response Parser is a custom class I've written to parse the elasticsearch json research as object.
    val response = ResponseParser.parseJSON(r.getResponseBody)
    // With the scroll id from within the response body you do all the subsequent request to receive the data from ES.
    val scrollRequest = client.scroll("10m", repsponse._scroll_id)
    scrollRequest onComplete {
      case Success(r) =>
        // Body contains the first part of the documents matching you query.
        var body = r.getResponseBody
      case Failure =>  

    }

    this.scrollNextPage(response._scroll_id)
  case Failure(e) => println("An error has occured: " + e.getMessage)
}
```
