### ISSUE TITLE
bump to scala 2.12.1

### ISSUE THREAD

**Issue by lincanli** [gphat/wabisabi#47]
Thank for this project. 
Can you bump to scala 2.12.1 and release it?

**Comment by gphat** [comment]
Looks like dispatch does not (yet?) have a 2.12 version, so I can't bump this up. :(

**Comment by larochef** [comment]
I'd like to see a 2.12.x version too :)

I have check dependencies and I saw them compiled for scala 2.12 with versions: 
- dispatch-core in version 0.12.0 
- grizzled in version 1.3.0, 
- scala-uri in version 0.4.16, 
- specs2 2.4.17
- argonaut in 6.2-RC2.

Hope it can help.

**Comment by gphat** [comment]
I've release 2.2.0 for 2.12 and 2.11, dropping 2.10. Thanks for the tips @larochef!
