### ISSUE TITLE
SBT consuming

### ISSUE THREAD

**Issue by dimastatz** [gphat/wabisabi#55]
Hi, I have a technical question ( it is not an issue )
I can see that wabisabi jar can be consumed by following way: 
        libraryDependencies += "com.github.gphat" %% "wabisabi" % "2.2.0"

Could you please explain a bit, where wabisabi.jar is actually located. In which repository ?
I would like to share my jar by the same way.

Thanks a lot.

**Comment by gphat** [comment]
Hey there,

You can see the plugins I use to publish the jar [here](https://github.com/gphat/wabisabi/tree/master/project).
